---
##########################
## Hadolint config file ##
##########################
ignored:
  - DL3018  # Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
  - DL3007  # Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag
  