name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker build
        shell: bash
        run: |
          set -o errexit
          set -o pipefail

          docker build -t azure-ddns:${GITHUB_SHA} .
      - name: Docker Push
        shell: bash
        run: |
          set -o errexit
          set -o pipefail

          cat ~/TOKEN.txt | docker login https://docker.pkg.github.com -u USERNAME --password-stdin
          docker tag azure-ddns:${GITHUB_SHA} docker.pkg.github.com/${GITHUB_REPOSITORY}/azure-ddns:${GITHUB_SHA}
          docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/azure-ddns:${GITHUB_SHA}
