name: Docker build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker build
        shell: bash
        run: |
          set -o errexit
          set -o pipefail

          docker build -t azure-ddns .
