name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker build
        shell: bash
        run: |
          docker build -t azure-ddns:${GITHUB_SHA} .
      - name: Test Image
        shell: bash
        run: |
          docker run --interactive --rm \
            -e CLIENT_ID="${{ secrets.CLIENT_ID }}" \
            -e CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" \
            -e TENANT_ID="${{ secrets.TENANT_ID }}" \
            -e RESOURCE_GROUP="${{ secrets.RESOURCE_GROUP }}" \
            -e DNSZONE="${{ secrets.DNSZONE }}" \
            -e RECORD_NAME="${{ secrets.RECORD_NAME }}" \
            -e COMMAND_IP="${{ secrets.COMMAND_IP }}" \
            azure-ddns:${GITHUB_SHA}
      - name: Docker Push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          OWNER=$(echo "${GITHUB_REPOSITORY}" | awk -F'/' '{print $1}')
          echo "::group::Parameters"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "OWNER            : ${OWNER}"
          echo "GITHUB_ACTOR     : ${GITHUB_ACTOR}"
          echo "GITHUB_SHA       : ${GITHUB_SHA}"
          echo "::endgroup::"

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
          docker tag azure-ddns:${GITHUB_SHA} ghcr.io/${OWNER}/azure-ddns:${GITHUB_SHA}
          docker push ghcr.io/${OWNER}/azure-ddns:${GITHUB_SHA}
          docker tag azure-ddns:${GITHUB_SHA} ghcr.io/${OWNER}/azure-ddns:latest
          docker push ghcr.io/${OWNER}/azure-ddns:latest
          docker logout https://ghcr.io
