name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: azure-ddns
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker build
        shell: bash
        run: |
          docker build -t ${IMAGE_NAME}:${GITHUB_SHA} .
      - name: Test Image
        shell: bash
        run: |
          docker run --interactive --rm \
            -e CLIENT_ID="${{ secrets.CLIENT_ID }}" \
            -e CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" \
            -e TENANT_ID="${{ secrets.TENANT_ID }}" \
            -e RESOURCE_GROUP="${{ secrets.RESOURCE_GROUP }}" \
            -e DNSZONE="${{ secrets.DNSZONE }}" \
            -e RECORD_NAMES="${{ secrets.RECORD_NAMES }}" \
            -e UPDATE_IP_CMD="${{ secrets.UPDATE_IP_CMD }}" \
            ${IMAGE_NAME}:${GITHUB_SHA}
      - name: Docker Push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        shell: bash
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REGISTRY_HOSTNAME: ghcr.io
        run: |
          echo "::group::Parameters"
          echo "REPOSITORY_OWNER : ${REPOSITORY_OWNER}"
          echo "REGISTRY_HOSTNAME: ${REGISTRY_HOSTNAME}"
          echo "GITHUB_ACTOR     : ${GITHUB_ACTOR}"
          echo "GITHUB_SHA       : ${GITHUB_SHA}"
          echo "::endgroup::"

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://${REGISTRY_HOSTNAME} -u "${GITHUB_ACTOR}" --password-stdin
          docker tag ${IMAGE_NAME}:${GITHUB_SHA} ${REGISTRY_HOSTNAME}/${REPOSITORY_OWNER}/${IMAGE_NAME}:${GITHUB_SHA}
          docker push ${REGISTRY_HOSTNAME}/${REPOSITORY_OWNER}/${IMAGE_NAME}:${GITHUB_SHA}
          docker tag ${IMAGE_NAME}:${GITHUB_SHA} ${REGISTRY_HOSTNAME}/${REPOSITORY_OWNER}/${IMAGE_NAME}:latest
          docker push ${REGISTRY_HOSTNAME}/${REPOSITORY_OWNER}/${IMAGE_NAME}:latest
          docker logout https://${REGISTRY_HOSTNAME}
