name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker build
        shell: bash
        run: |
          echo "GITHUB_REF     : ${GITHUB_REF}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          
          #docker build -t azure-ddns:${GITHUB_SHA} .
      # - name: Docker Push
      #   if: ${{ github.event_name == 'pull_request' }}
      #   shell: bash
      #   run: |
      #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u "${GITHUB_ACTOR}" --password-stdin
      #     docker tag azure-ddns:${GITHUB_SHA} docker.pkg.github.com/${GITHUB_REPOSITORY}/azure-ddns:${GITHUB_SHA}
      #     docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/azure-ddns:${GITHUB_SHA}
      #     docker tag azure-ddns:${GITHUB_SHA} docker.pkg.github.com/${GITHUB_REPOSITORY}/azure-ddns:${GITHUB_HEAD_REF}
      #     docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/azure-ddns:${GITHUB_HEAD_REF}
      #     docker logout https://docker.pkg.github.com
